{% set name = "netifaces" %}
{% set version = "0.10.8" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_val = "befc9800751991c005fcc24e75be90c5752e5c1907ed4fa4efa17adfcc09d490" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash_val }}

build:
  number: 0
  script: python -m pip install --no-deps -vv --ignore-installed .
  skip: True # [py<36]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip

  run:
    - python

test:
  requires:
    - pytest
  imports:
    - {{ name }}
  commands:
    - pytest test.py

about:
  home: https://github.com/al45tair/netifaces
  license: MIT
  license_family: MIT
  summary: 'Portable network interface information.'
  dev_url: https://github.com/al45tair/netifaces

extra:
  recipe-maintainers:
    - anguslees
    - minrk
    - pmlandwehr
