{% set name = "netifaces" %}
{% set version = "0.11.0" %}
{% set sha256 = "043a79146eb2907edf439899f262b3dfe41717d34124298ed281139a8b93ca32" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [py<36]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - {{ name }}

about:
  home: https://github.com/al45tair/netifaces
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: Portable network interface information
  dev_url: https://github.com/al45tair/netifaces
